amazon.aws.dynamodb.endpoint=http://localhost:8000/
amazon.aws.dynamodb.accesskey=key
amazon.aws.dynamodb.secretkey=key2
amazon.aws.dynamodb.region=eu-north-1
amazon.aws.dynamodb.table=preparedness

#logging.level.org.springframework.boot.autoconfigure=ERROR

# Swagger
# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html
# API docs path
springdoc.api-docs.path=/v3/api-docs
# Enable/disable API docs
springdoc.api-docs.enabled=true
# Enable/disable Swagger UI
springdoc.swagger-ui.enabled=true