#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.url=jdbc:postgresql://db.fhbkafnydplkaqyhqtxm.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=${DATABASE_PASSWORD}
#spring.datasource.password=postgres_admin
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate

#logging.level.org.springframework.boot.autoconfigure=ERROR

# Swagger
# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html
# API docs path
springdoc.api-docs.path=/v3/api-docs
# Enable/disable API docs
springdoc.api-docs.enabled=true
# Enable/disable Swagger UI
springdoc.swagger-ui.enabled=true
mail.username=kjetiltorvund@gmail.com
mail.password=${MAIL_PASSWORD}
# Supabase settings
supabase.url=${SUPABASE_URL}
supabase.apiKey=${SUPABASE_SECRET_API_KEY}
