server {
  listen 80;
  cefeda05-65b0-4aed-9c4f-f7fb3e63509b 45-248-37-116.cloud-xip.com;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    proxy_pass http://api:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}

docker compose run --rm certbot certonly \
  --webroot -w /var/www/certbot \
  -d 45-248-37-116.cloud-xip.com \
  --email kjetiltorvund@gmail.com --agree-tos --no-eff-email