name: Build Java Project
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-java:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Install Maven (for act compatibility)
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Validate required environment variables
        env:
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          SUPABASE_SECRET_API_KEY: ${{ secrets.SUPABASE_SECRET_API_KEY }}
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
        run: |
          [ -n "$MAIL_PASSWORD" ] || { echo "MAIL_PASSWORD is missing"; exit 1; }
          [ -n "$SUPABASE_SECRET_API_KEY" ] || { echo "SUPABASE_SECRET_API_KEY is missing"; exit 1; }
          [ -n "$SUPABASE_URL" ] || { echo "SUPABASE_URL is missing"; exit 1; }

      - name: Build with Maven
        env:
          # secrets
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          SUPABASE_PUB_API_KEY: ${{ secrets.SUPABASE_PUB_API_KEY }}
          SUPABASE_SECRET_API_KEY: ${{ secrets.SUPABASE_SECRET_API_KEY }}
          # variable
          MAIL_USERNAME: ${{ vars.MAIL_USERNAME }}
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
        run: mvn clean package
